backend:
  name: git-gateway
  branch: master

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.html"
        fields:
          - { label: "Body", name: "body", widget: "text" }
      - label: "Uni Page"
        name: "uni"
        file: "uni.html"
        fields:
          - { label: "Body", name: "body", widget: "text" }
      - label: "Career Page"
        name: "career"
        file: "career.html"
        fields:
          - { label: "Body", name: "body", widget: "text" }
      - label: "Life Page"
        name: "life"
        file: "life.html"
        fields:
          - { label: "Body", name: "body", widget: "text" }
      - label: "Workshops Page"
        name: "workshops"
        file: "workshops.html"
        fields:
          - { label: "Body", name: "body", widget: "text" }
      - label: "Proofreading Page"
        name: "proofreading"
        file: "proofreading.html"
        fields:
          - { label: "Body", name: "body", widget: "text" }
